

require 'spec_helper'
require 'json'

# Unit tests for TerapiClient::ApiProxyApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApiProxyApi' do
  before do
    # run before each test
    @instance = TerapiClient::ApiProxyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiProxyApi' do
    it 'should create an instance of ApiProxyApi' do
      expect(@instance).to be_instance_of(TerapiClient::ApiProxyApi)
    end
  end

  # unit tests for api_proxy_endpoint_delete
  # 21_997
  # ### Error Codes  | Code | Name | Message |  | :--- | :--- | :--- |  | 21_997_101 | TenantNotFound |  |  | 21_997_102 | IntegrationNotFound |  |  | 21_997_103 | UnknownExceptionWhenCallingThirdPartyApi |  |  | 21_997_104 | UnknownExceptionWhenCallAction |  |  | 21_997_105 | IntegrationIsNotEnabled |  |
  # @param x_tenant_id 
  # @param integration_name 
  # @param endpoint 
  # @param [Hash] opts the optional parameters
  # @option opts [ApiproxyEndpointBody6] :body 
  # @return [CallActionResponse]
  describe 'api_proxy_endpoint_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_proxy_endpoint_get
  # 21_997
  # ### Error Codes  | Code | Name | Message |  | :--- | :--- | :--- |  | 21_997_101 | TenantNotFound |  |  | 21_997_102 | IntegrationNotFound |  |  | 21_997_103 | UnknownExceptionWhenCallingThirdPartyApi |  |  | 21_997_104 | UnknownExceptionWhenCallAction |  |  | 21_997_105 | IntegrationIsNotEnabled |  |
  # @param integration_name 
  # @param endpoint 
  # @param x_tenant_id 
  # @param [Hash] opts the optional parameters
  # @return [CallActionResponse]
  describe 'api_proxy_endpoint_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_proxy_endpoint_patch
  # 21_997
  # ### Error Codes  | Code | Name | Message |  | :--- | :--- | :--- |  | 21_997_101 | TenantNotFound |  |  | 21_997_102 | IntegrationNotFound |  |  | 21_997_103 | UnknownExceptionWhenCallingThirdPartyApi |  |  | 21_997_104 | UnknownExceptionWhenCallAction |  |  | 21_997_105 | IntegrationIsNotEnabled |  |
  # @param x_tenant_id 
  # @param integration_name 
  # @param endpoint 
  # @param [Hash] opts the optional parameters
  # @option opts [ApiproxyEndpointBody9] :body 
  # @return [CallActionResponse]
  describe 'api_proxy_endpoint_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_proxy_endpoint_post
  # 21_997
  # ### Error Codes  | Code | Name | Message |  | :--- | :--- | :--- |  | 21_997_101 | TenantNotFound |  |  | 21_997_102 | IntegrationNotFound |  |  | 21_997_103 | UnknownExceptionWhenCallingThirdPartyApi |  |  | 21_997_104 | UnknownExceptionWhenCallAction |  |  | 21_997_105 | IntegrationIsNotEnabled |  |
  # @param x_tenant_id 
  # @param integration_name 
  # @param endpoint 
  # @param [Hash] opts the optional parameters
  # @option opts [ApiproxyEndpointBody3] :body 
  # @return [CallActionResponse]
  describe 'api_proxy_endpoint_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_proxy_endpoint_put
  # 21_997
  # ### Error Codes  | Code | Name | Message |  | :--- | :--- | :--- |  | 21_997_101 | TenantNotFound |  |  | 21_997_102 | IntegrationNotFound |  |  | 21_997_103 | UnknownExceptionWhenCallingThirdPartyApi |  |  | 21_997_104 | UnknownExceptionWhenCallAction |  |  | 21_997_105 | IntegrationIsNotEnabled |  |
  # @param x_tenant_id 
  # @param integration_name 
  # @param endpoint 
  # @param [Hash] opts the optional parameters
  # @option opts [ApiproxyEndpointBody] :body 
  # @return [CallActionResponse]
  describe 'api_proxy_endpoint_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_proxy_oauth2_challenge_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tenant_id 
  # @return [OAuth2ChallengeDtoResponse]
  describe 'api_proxy_oauth2_challenge_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_proxy_unified_contacts_external_id_get
  # @param external_id 
  # @param [Hash] opts the optional parameters
  # @return [UnifiedContactResponse]
  describe 'api_proxy_unified_contacts_external_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_proxy_unified_contacts_get
  # @param [Hash] opts the optional parameters
  # @return [UnifiedContactsListResponse]
  describe 'api_proxy_unified_contacts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
