

require 'spec_helper'
require 'json'

# Unit tests for TerapiClient::ApplicationApiKeyApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApplicationApiKeyApi' do
  before do
    # run before each test
    @instance = TerapiClient::ApplicationApiKeyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplicationApiKeyApi' do
    it 'should create an instance of ApplicationApiKeyApi' do
      expect(@instance).to be_instance_of(TerapiClient::ApplicationApiKeyApi)
    end
  end

  # unit tests for application_apikey_generate_post
  # 16_999
  # ### Error Codes  | Code | Name | Message |  | :--- | :--- | :--- |  | 16_999_101 | ApplicationNotFound | Application not found. |  | 16_999_102 | UnknownExceptionWhenCheckApplicationExistence | Unknown exception when checking if application exists. |  | 16_999_103 | UnknownExceptionWhenGenerateApplicationApiKey | Unknown exception when generating application API key. |
  # @param [Hash] opts the optional parameters
  # @option opts [ApplicationapikeyGenerateBody] :body 
  # @return [CreateApplicationApiKeyResponse]
  describe 'application_apikey_generate_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for application_apikey_get_by_application_id_get
  # 16_995
  # ### Error Codes  | Code | Name | Message |  | :--- | :--- | :--- |  | 16_995_101 | ApplicationApiKeyNotFound | Application API key not found. |  | 16_995_102 | UnknownExceptionWhenTryingFetchApplications | Unknown exception when trying to fetch applications. |
  # @param [Hash] opts the optional parameters
  # @option opts [String] :application_id 
  # @return [ApplicationApiKeyByApplicationIdResponse]
  describe 'application_apikey_get_by_application_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for application_apikey_revoke_delete
  # 16_998
  # ### Error Codes  | Code | Name | Message |  | :--- | :--- | :--- |  | 16_998_101 | ApplicationApiKeyNotFound | Application API key not found. |  | 16_998_102 | UnknownExceptionWhenCheckApplicationExistence | Unknown exception when checking if application exists. |  | 16_998_103 | UnknownExceptionWhenGenerateApplicationApiKey | Unknown exception when generating application API key. |
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id 
  # @return [RevokeApplicationApiKeyResponse]
  describe 'application_apikey_revoke_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
