

require 'spec_helper'
require 'json'

# Unit tests for TerapiClient::IntegrationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'IntegrationApi' do
  before do
    # run before each test
    @instance = TerapiClient::IntegrationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IntegrationApi' do
    it 'should create an instance of IntegrationApi' do
      expect(@instance).to be_instance_of(TerapiClient::IntegrationApi)
    end
  end

  # unit tests for integration_get_get
  # 17_997
  # ### Error Codes  | Code | Name | Message |  | :--- | :--- | :--- |  | 17_997_101 | UnknownExceptionWhenTryingFetchOneIntegration |  |
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id 
  # @return [GetOneIntegrationResponse]
  describe 'integration_get_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for integration_list_get
  # 17_999
  # ### Error Codes  | Code | Name | Message |  | :--- | :--- | :--- |  | 17_999_101 | UnknownExceptionWhenTryingFetchIntegrations | Unknown exception when trying to fetch integrations. |
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :search_keyword 
  # @option opts [String] :category_id 
  # @return [IntegrationListResponse]
  describe 'integration_list_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
