

require 'spec_helper'
require 'json'

# Unit tests for TerapiClient::StatisticsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StatisticsApi' do
  before do
    # run before each test
    @instance = TerapiClient::StatisticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatisticsApi' do
    it 'should create an instance of StatisticsApi' do
      expect(@instance).to be_instance_of(TerapiClient::StatisticsApi)
    end
  end

  # unit tests for statistics_user_profile_get
  # 14_997
  # ### Error Codes  | Code | Name | Message |  | :--- | :--- | :--- |  | 14_997_101 | UserNotFound | User not found. |  | 14_997_102 | UserDoesNotHaveActiveSubscription | User does not have an active subscription. |  | 14_997_103 | UnknownExceptionWhenFetchUserProfileStatistics | Unknown exception when fetching user profile statistics. |
  # @param [Hash] opts the optional parameters
  # @return [UserProfileStatisticsResponse]
  describe 'statistics_user_profile_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
