

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AddIntegrationToApplicationRequestErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AddIntegrationToApplicationRequestErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::AddIntegrationToApplicationRequestErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AddIntegrationToApplicationRequestErrorCodes' do
    it 'should create an instance of AddIntegrationToApplicationRequestErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::AddIntegrationToApplicationRequestErrorCodes)
    end
  end
end
