

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfCallActionErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfCallActionErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfCallActionErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfCallActionErrorCode' do
    it 'should create an instance of AllOfCallActionErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfCallActionErrorCode)
    end
  end
end
