

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfInviteTenantByApplicationIntegrationIdErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfInviteTenantByApplicationIntegrationIdErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfInviteTenantByApplicationIntegrationIdErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfInviteTenantByApplicationIntegrationIdErrorCode' do
    it 'should create an instance of AllOfInviteTenantByApplicationIntegrationIdErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfInviteTenantByApplicationIntegrationIdErrorCode)
    end
  end
end
