

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfUserProfileStatisticsErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfUserProfileStatisticsErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfUserProfileStatisticsErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfUserProfileStatisticsErrorCode' do
    it 'should create an instance of AllOfUserProfileStatisticsErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfUserProfileStatisticsErrorCode)
    end
  end
end
