

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfGetOneIntegrationErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfGetOneIntegrationErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfGetOneIntegrationErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfGetOneIntegrationErrorCode' do
    it 'should create an instance of AllOfGetOneIntegrationErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfGetOneIntegrationErrorCode)
    end
  end
end
