

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfTenantDtoInvitationStatus
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfTenantDtoInvitationStatus' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfTenantDtoInvitationStatus.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfTenantDtoInvitationStatus' do
    it 'should create an instance of AllOfTenantDtoInvitationStatus' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfTenantDtoInvitationStatus)
    end
  end
end
