

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfUnifiedContactsListResponseError
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfUnifiedContactsListResponseError' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfUnifiedContactsListResponseError.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfUnifiedContactsListResponseError' do
    it 'should create an instance of AllOfUnifiedContactsListResponseError' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfUnifiedContactsListResponseError)
    end
  end
  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "values"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
