

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfCategoryListErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfCategoryListErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfCategoryListErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfCategoryListErrorType' do
    it 'should create an instance of AllOfCategoryListErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfCategoryListErrorType)
    end
  end
end
