

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfRefreshAuthenticationTokenErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfRefreshAuthenticationTokenErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfRefreshAuthenticationTokenErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfRefreshAuthenticationTokenErrorType' do
    it 'should create an instance of AllOfRefreshAuthenticationTokenErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfRefreshAuthenticationTokenErrorType)
    end
  end
end
