

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfInviteTenantByApplicationIntegrationIdErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfInviteTenantByApplicationIntegrationIdErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfInviteTenantByApplicationIntegrationIdErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfInviteTenantByApplicationIntegrationIdErrorType' do
    it 'should create an instance of AllOfInviteTenantByApplicationIntegrationIdErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfInviteTenantByApplicationIntegrationIdErrorType)
    end
  end
end
