

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfUpdateTenantConnectionErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfUpdateTenantConnectionErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfUpdateTenantConnectionErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfUpdateTenantConnectionErrorType' do
    it 'should create an instance of AllOfUpdateTenantConnectionErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfUpdateTenantConnectionErrorType)
    end
  end
end
