

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfUserProfileStatisticsErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfUserProfileStatisticsErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfUserProfileStatisticsErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfUserProfileStatisticsErrorType' do
    it 'should create an instance of AllOfUserProfileStatisticsErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfUserProfileStatisticsErrorType)
    end
  end
end
