

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfDeleteApplicationErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfDeleteApplicationErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfDeleteApplicationErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfDeleteApplicationErrorType' do
    it 'should create an instance of AllOfDeleteApplicationErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfDeleteApplicationErrorType)
    end
  end
end
