

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfUserTenantListErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfUserTenantListErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfUserTenantListErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfUserTenantListErrorCode' do
    it 'should create an instance of AllOfUserTenantListErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfUserTenantListErrorCode)
    end
  end
end
