

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfUpdateTenantConnectionErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfUpdateTenantConnectionErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfUpdateTenantConnectionErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfUpdateTenantConnectionErrorCode' do
    it 'should create an instance of AllOfUpdateTenantConnectionErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfUpdateTenantConnectionErrorCode)
    end
  end
end
