

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfGetAuthenticationTokenErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfGetAuthenticationTokenErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfGetAuthenticationTokenErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfGetAuthenticationTokenErrorCode' do
    it 'should create an instance of AllOfGetAuthenticationTokenErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfGetAuthenticationTokenErrorCode)
    end
  end
end
