

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfCreateApplicationApiKeyRequestDto
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfCreateApplicationApiKeyRequestDto' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfCreateApplicationApiKeyRequestDto.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfCreateApplicationApiKeyRequestDto' do
    it 'should create an instance of AllOfCreateApplicationApiKeyRequestDto' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfCreateApplicationApiKeyRequestDto)
    end
  end
  describe 'test attribute "web_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ip_addresses"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "application_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
