

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfCreateApplicationErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfCreateApplicationErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfCreateApplicationErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfCreateApplicationErrorCode' do
    it 'should create an instance of AllOfCreateApplicationErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfCreateApplicationErrorCode)
    end
  end
end
