

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfInviteTenantErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfInviteTenantErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfInviteTenantErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfInviteTenantErrorCode' do
    it 'should create an instance of AllOfInviteTenantErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfInviteTenantErrorCode)
    end
  end
end
