

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfAddIntegrationToApplicationErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfAddIntegrationToApplicationErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfAddIntegrationToApplicationErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfAddIntegrationToApplicationErrorType' do
    it 'should create an instance of AllOfAddIntegrationToApplicationErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfAddIntegrationToApplicationErrorType)
    end
  end
end
