

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfErrorType' do
    it 'should create an instance of AllOfErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfErrorType)
    end
  end
end
