

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfCreateApplicationApiKeyErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfCreateApplicationApiKeyErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfCreateApplicationApiKeyErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfCreateApplicationApiKeyErrorType' do
    it 'should create an instance of AllOfCreateApplicationApiKeyErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfCreateApplicationApiKeyErrorType)
    end
  end
end
