

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfCreateUserProfileErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfCreateUserProfileErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfCreateUserProfileErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfCreateUserProfileErrorCode' do
    it 'should create an instance of AllOfCreateUserProfileErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfCreateUserProfileErrorCode)
    end
  end
end
