

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfDeclineTenantInvitationErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfDeclineTenantInvitationErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfDeclineTenantInvitationErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfDeclineTenantInvitationErrorCode' do
    it 'should create an instance of AllOfDeclineTenantInvitationErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfDeclineTenantInvitationErrorCode)
    end
  end
end
