

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfRefreshAuthenticationTokenErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfRefreshAuthenticationTokenErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfRefreshAuthenticationTokenErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfRefreshAuthenticationTokenErrorCode' do
    it 'should create an instance of AllOfRefreshAuthenticationTokenErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfRefreshAuthenticationTokenErrorCode)
    end
  end
end
