

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfDeclineTenantInvitationErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfDeclineTenantInvitationErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfDeclineTenantInvitationErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfDeclineTenantInvitationErrorType' do
    it 'should create an instance of AllOfDeclineTenantInvitationErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfDeclineTenantInvitationErrorType)
    end
  end
end
