

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfApplicationApiKeyByApplicationIdErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfApplicationApiKeyByApplicationIdErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfApplicationApiKeyByApplicationIdErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfApplicationApiKeyByApplicationIdErrorCode' do
    it 'should create an instance of AllOfApplicationApiKeyByApplicationIdErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfApplicationApiKeyByApplicationIdErrorCode)
    end
  end
end
