

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfUpdateApplicationErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfUpdateApplicationErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfUpdateApplicationErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfUpdateApplicationErrorCode' do
    it 'should create an instance of AllOfUpdateApplicationErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfUpdateApplicationErrorCode)
    end
  end
end
