

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfCategoryListErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfCategoryListErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfCategoryListErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfCategoryListErrorCode' do
    it 'should create an instance of AllOfCategoryListErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfCategoryListErrorCode)
    end
  end
end
