

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfApplicationIntegrationListByApplicationIdResponseData
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfApplicationIntegrationListByApplicationIdResponseData' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfApplicationIntegrationListByApplicationIdResponseData.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfApplicationIntegrationListByApplicationIdResponseData' do
    it 'should create an instance of AllOfApplicationIntegrationListByApplicationIdResponseData' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfApplicationIntegrationListByApplicationIdResponseData)
    end
  end
  describe 'test attribute "total_records"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "current_page"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "per_page"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "items"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
