

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfCallActionErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfCallActionErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfCallActionErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfCallActionErrorType' do
    it 'should create an instance of AllOfCallActionErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfCallActionErrorType)
    end
  end
end
