

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfGetAuthenticationTokenErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfGetAuthenticationTokenErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfGetAuthenticationTokenErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfGetAuthenticationTokenErrorType' do
    it 'should create an instance of AllOfGetAuthenticationTokenErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfGetAuthenticationTokenErrorType)
    end
  end
end
