

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfIntegrationListErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfIntegrationListErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfIntegrationListErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfIntegrationListErrorType' do
    it 'should create an instance of AllOfIntegrationListErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfIntegrationListErrorType)
    end
  end
end
