

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfApplicationIntegrationListByApplicationIdErrorCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfApplicationIntegrationListByApplicationIdErrorCode' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfApplicationIntegrationListByApplicationIdErrorCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfApplicationIntegrationListByApplicationIdErrorCode' do
    it 'should create an instance of AllOfApplicationIntegrationListByApplicationIdErrorCode' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfApplicationIntegrationListByApplicationIdErrorCode)
    end
  end
end
