

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfCreateUserProfileErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfCreateUserProfileErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfCreateUserProfileErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfCreateUserProfileErrorType' do
    it 'should create an instance of AllOfCreateUserProfileErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfCreateUserProfileErrorType)
    end
  end
end
