

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfApplicationIntegrationListByApplicationIdErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfApplicationIntegrationListByApplicationIdErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfApplicationIntegrationListByApplicationIdErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfApplicationIntegrationListByApplicationIdErrorType' do
    it 'should create an instance of AllOfApplicationIntegrationListByApplicationIdErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfApplicationIntegrationListByApplicationIdErrorType)
    end
  end
end
