

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfCreateApplicationErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfCreateApplicationErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfCreateApplicationErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfCreateApplicationErrorType' do
    it 'should create an instance of AllOfCreateApplicationErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfCreateApplicationErrorType)
    end
  end
end
