

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::AllOfUserProfileStatisticsResponseData
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllOfUserProfileStatisticsResponseData' do
  before do
    # run before each test
    @instance = TerapiClient::AllOfUserProfileStatisticsResponseData.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllOfUserProfileStatisticsResponseData' do
    it 'should create an instance of AllOfUserProfileStatisticsResponseData' do
      expect(@instance).to be_instance_of(TerapiClient::AllOfUserProfileStatisticsResponseData)
    end
  end
  describe 'test attribute "available_integrations"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "available_api_calls"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "applications_count"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
