

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::ApiproxyEndpointBody4
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApiproxyEndpointBody4' do
  before do
    # run before each test
    @instance = TerapiClient::ApiproxyEndpointBody4.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiproxyEndpointBody4' do
    it 'should create an instance of ApiproxyEndpointBody4' do
      expect(@instance).to be_instance_of(TerapiClient::ApiproxyEndpointBody4)
    end
  end
  describe 'test attribute "body"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
