

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::ApiproxyEndpointBody11
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApiproxyEndpointBody11' do
  before do
    # run before each test
    @instance = TerapiClient::ApiproxyEndpointBody11.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiproxyEndpointBody11' do
    it 'should create an instance of ApiproxyEndpointBody11' do
      expect(@instance).to be_instance_of(TerapiClient::ApiproxyEndpointBody11)
    end
  end
  describe 'test attribute "body"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
