

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::ApiproxyEndpointBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApiproxyEndpointBody' do
  before do
    # run before each test
    @instance = TerapiClient::ApiproxyEndpointBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiproxyEndpointBody' do
    it 'should create an instance of ApiproxyEndpointBody' do
      expect(@instance).to be_instance_of(TerapiClient::ApiproxyEndpointBody)
    end
  end
  describe 'test attribute "body"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
