

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::ApplicationApiKeyByApplicationIdErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApplicationApiKeyByApplicationIdErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::ApplicationApiKeyByApplicationIdErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplicationApiKeyByApplicationIdErrorCodes' do
    it 'should create an instance of ApplicationApiKeyByApplicationIdErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::ApplicationApiKeyByApplicationIdErrorCodes)
    end
  end
end
