

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::ApplicationIntegrationListByApplicationIdRequestErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApplicationIntegrationListByApplicationIdRequestErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::ApplicationIntegrationListByApplicationIdRequestErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplicationIntegrationListByApplicationIdRequestErrorCodes' do
    it 'should create an instance of ApplicationIntegrationListByApplicationIdRequestErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::ApplicationIntegrationListByApplicationIdRequestErrorCodes)
    end
  end
end
