

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::ApplicationIntegrationDto
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApplicationIntegrationDto' do
  before do
    # run before each test
    @instance = TerapiClient::ApplicationIntegrationDto.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplicationIntegrationDto' do
    it 'should create an instance of ApplicationIntegrationDto' do
      expect(@instance).to be_instance_of(TerapiClient::ApplicationIntegrationDto)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "application"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "integration"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
