

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::ApplicationintegrationAddintegrationtoapplicationBody1
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApplicationintegrationAddintegrationtoapplicationBody1' do
  before do
    # run before each test
    @instance = TerapiClient::ApplicationintegrationAddintegrationtoapplicationBody1.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplicationintegrationAddintegrationtoapplicationBody1' do
    it 'should create an instance of ApplicationintegrationAddintegrationtoapplicationBody1' do
      expect(@instance).to be_instance_of(TerapiClient::ApplicationintegrationAddintegrationtoapplicationBody1)
    end
  end
  describe 'test attribute "dto"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
