

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::CategoryDto
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CategoryDto' do
  before do
    # run before each test
    @instance = TerapiClient::CategoryDto.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CategoryDto' do
    it 'should create an instance of CategoryDto' do
      expect(@instance).to be_instance_of(TerapiClient::CategoryDto)
    end
  end
  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "is_parent"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "parent_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
