

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::CategoryListRequestErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CategoryListRequestErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::CategoryListRequestErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CategoryListRequestErrorCodes' do
    it 'should create an instance of CategoryListRequestErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::CategoryListRequestErrorCodes)
    end
  end
end
