

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::ClientErrorType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClientErrorType' do
  before do
    # run before each test
    @instance = TerapiClient::ClientErrorType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClientErrorType' do
    it 'should create an instance of ClientErrorType' do
      expect(@instance).to be_instance_of(TerapiClient::ClientErrorType)
    end
  end
end
