

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::CreateUserProfileRequestErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CreateUserProfileRequestErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::CreateUserProfileRequestErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateUserProfileRequestErrorCodes' do
    it 'should create an instance of CreateUserProfileRequestErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::CreateUserProfileRequestErrorCodes)
    end
  end
end
