

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::CreateApplicationRequestErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CreateApplicationRequestErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::CreateApplicationRequestErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateApplicationRequestErrorCodes' do
    it 'should create an instance of CreateApplicationRequestErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::CreateApplicationRequestErrorCodes)
    end
  end
end
