

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::CreateApplicationApiKeyRequestErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CreateApplicationApiKeyRequestErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::CreateApplicationApiKeyRequestErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateApplicationApiKeyRequestErrorCodes' do
    it 'should create an instance of CreateApplicationApiKeyRequestErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::CreateApplicationApiKeyRequestErrorCodes)
    end
  end
end
