

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::DeclineTenantInvitationRequestErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DeclineTenantInvitationRequestErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::DeclineTenantInvitationRequestErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeclineTenantInvitationRequestErrorCodes' do
    it 'should create an instance of DeclineTenantInvitationRequestErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::DeclineTenantInvitationRequestErrorCodes)
    end
  end
end
