

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::DeleteApplicationRequestErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DeleteApplicationRequestErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::DeleteApplicationRequestErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeleteApplicationRequestErrorCodes' do
    it 'should create an instance of DeleteApplicationRequestErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::DeleteApplicationRequestErrorCodes)
    end
  end
end
