

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::IntegrationListRequestErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'IntegrationListRequestErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::IntegrationListRequestErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IntegrationListRequestErrorCodes' do
    it 'should create an instance of IntegrationListRequestErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::IntegrationListRequestErrorCodes)
    end
  end
end
