

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::IntegrationEndpointDto
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'IntegrationEndpointDto' do
  before do
    # run before each test
    @instance = TerapiClient::IntegrationEndpointDto.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IntegrationEndpointDto' do
    it 'should create an instance of IntegrationEndpointDto' do
      expect(@instance).to be_instance_of(TerapiClient::IntegrationEndpointDto)
    end
  end
  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "fields"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
