

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::InvitationStatus1
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InvitationStatus1' do
  before do
    # run before each test
    @instance = TerapiClient::InvitationStatus1.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvitationStatus1' do
    it 'should create an instance of InvitationStatus1' do
      expect(@instance).to be_instance_of(TerapiClient::InvitationStatus1)
    end
  end
end
