

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::InviteTenantByApplicationIntegrationIdRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InviteTenantByApplicationIntegrationIdRequest' do
  before do
    # run before each test
    @instance = TerapiClient::InviteTenantByApplicationIntegrationIdRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InviteTenantByApplicationIntegrationIdRequest' do
    it 'should create an instance of InviteTenantByApplicationIntegrationIdRequest' do
      expect(@instance).to be_instance_of(TerapiClient::InviteTenantByApplicationIntegrationIdRequest)
    end
  end
  describe 'test attribute "dto"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
