

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::OAuth2ChallengeDto
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OAuth2ChallengeDto' do
  before do
    # run before each test
    @instance = TerapiClient::OAuth2ChallengeDto.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OAuth2ChallengeDto' do
    it 'should create an instance of OAuth2ChallengeDto' do
      expect(@instance).to be_instance_of(TerapiClient::OAuth2ChallengeDto)
    end
  end
  describe 'test attribute "redirect_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "tokens"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
