

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::RefreshAuthenticationTokenDto
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RefreshAuthenticationTokenDto' do
  before do
    # run before each test
    @instance = TerapiClient::RefreshAuthenticationTokenDto.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RefreshAuthenticationTokenDto' do
    it 'should create an instance of RefreshAuthenticationTokenDto' do
      expect(@instance).to be_instance_of(TerapiClient::RefreshAuthenticationTokenDto)
    end
  end
  describe 'test attribute "access_token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "expires_in"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
