

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::Response
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Response' do
  before do
    # run before each test
    @instance = TerapiClient::Response.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Response' do
    it 'should create an instance of Response' do
      expect(@instance).to be_instance_of(TerapiClient::Response)
    end
  end
  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "success"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
