

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::RevokeApplicationApiKeyResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RevokeApplicationApiKeyResponse' do
  before do
    # run before each test
    @instance = TerapiClient::RevokeApplicationApiKeyResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RevokeApplicationApiKeyResponse' do
    it 'should create an instance of RevokeApplicationApiKeyResponse' do
      expect(@instance).to be_instance_of(TerapiClient::RevokeApplicationApiKeyResponse)
    end
  end
  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "success"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
