

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::UpdateApplicationRequestErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UpdateApplicationRequestErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::UpdateApplicationRequestErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdateApplicationRequestErrorCodes' do
    it 'should create an instance of UpdateApplicationRequestErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::UpdateApplicationRequestErrorCodes)
    end
  end
end
