

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::UpdateTenantConnectionRequestDto
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UpdateTenantConnectionRequestDto' do
  before do
    # run before each test
    @instance = TerapiClient::UpdateTenantConnectionRequestDto.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdateTenantConnectionRequestDto' do
    it 'should create an instance of UpdateTenantConnectionRequestDto' do
      expect(@instance).to be_instance_of(TerapiClient::UpdateTenantConnectionRequestDto)
    end
  end
  describe 'test attribute "tenant_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "client_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "client_secret"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "scope"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
