

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::UserApplicationListRequestErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserApplicationListRequestErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::UserApplicationListRequestErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserApplicationListRequestErrorCodes' do
    it 'should create an instance of UserApplicationListRequestErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::UserApplicationListRequestErrorCodes)
    end
  end
end
