

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::UserProfileStatisticsErrorCodes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserProfileStatisticsErrorCodes' do
  before do
    # run before each test
    @instance = TerapiClient::UserProfileStatisticsErrorCodes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserProfileStatisticsErrorCodes' do
    it 'should create an instance of UserProfileStatisticsErrorCodes' do
      expect(@instance).to be_instance_of(TerapiClient::UserProfileStatisticsErrorCodes)
    end
  end
end
