

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TerapiClient::UserProfileStatisticsResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserProfileStatisticsResponse' do
  before do
    # run before each test
    @instance = TerapiClient::UserProfileStatisticsResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserProfileStatisticsResponse' do
    it 'should create an instance of UserProfileStatisticsResponse' do
      expect(@instance).to be_instance_of(TerapiClient::UserProfileStatisticsResponse)
    end
  end
  describe 'test attribute "success"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
